spring:
  sql:
    init:
      mode: never
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        #        show_sql: true
        #        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
    hibernate:
      ddl-auto: none
    open-in-view: false   # osiv 설정
  jwt:
    key: ${JWT_KEY}
  sigs:
    key: ${CONSUMER_KEY}
    secret: ${CONSUMER_SECRET}
  weather:
    key: ${METEOROLOGICAL_ADMIN_KEY}
  kakao:
    admin_key: ${KAKAO_SERVICE_ADMIN_KEY}
  profiles:
    active: ${PROFILE_TYPE} # dev: 개발서버 / prod: 운영서버
  servlet:
    multipart:
      enabled: true
      location: /uploadImg
      max-request-size: 30MB
      max-file-size: 10MB

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10s


logging:
  level:
    root: info
log:
  config:
    path: /customLog
    filename: custom

api:
  weather:
    service-key: ${SHORT_TERM_FORECAST_API_KEY}
    data-type: JSON

management:
  health:
    db:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: weather-pknu-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  tomcat:
    mbeanregistry:
      enabled: true

apple:
  public-key-url: https://appleid.apple.com
  client-id: ${CLIENT_ID}
  team-id: ${TEAM_ID}
  key:
    id: ${APPLE_KEY_ID}
    content: ${APPLE_KEY}
